server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:./data/renovatio.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect

renovatio:
  equivalence:
    baseline-command: []
    baseline-working-directory: ""
    candidate-command: []
    candidate-working-directory: ""
  reusable-assets:
    root: ${user.home}/.renovatio
  api:
    async:
      core-pool-size: 4
      max-pool-size: 8
      queue-capacity: 100
