package org.shark.renovatio.cobol.ir.annotated;

public enum AnnotatedNodeKind {
    DATA_ITEM, LEVEL_88_CONDITION, LEVEL_88_VALUE, PARAGRAPH,
    MOVE_STATEMENT, COMPUTE_STATEMENT, IF_STATEMENT, EVALUATE_STATEMENT, EVALUATE_BRANCH,
    PERFORM_STATEMENT, CALL_STATEMENT, DB2_STATEMENT, FILE_OPERATION_STATEMENT,
    LITERAL_EXPRESSION, DATA_REFERENCE_EXPRESSION, UNARY_ARITHMETIC_EXPRESSION,
    BINARY_ARITHMETIC_EXPRESSION, COMPARISON_CONDITION, BOOLEAN_CONDITION,
    NEGATED_CONDITION, LEVEL_88_CONDITION_REFERENCE
}
