package org.shark.renovatio.provider.cobol.pipeline;

import java.nio.file.Path;
import java.util.List;
import java.util.regex.Pattern;

/**
 * Normalizes metadata in generated files for determinism testing.
 * Replaces dynamic values with canonical placeholders.
 */
public class MetadataNormalizer {
    
    private static final List<Pattern> NORMALIZATION_PATTERNS = List.of(
        // Timestamps
        Pattern.compile("Generated at.*\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}.*"),
        Pattern.compile("// Generated:.*\\d{4}-\\d{2}-\\d{2}.*"),
        
        // Source hashes
        Pattern.compile("Source hash:.*[a-f0-9]{64}"),
        Pattern.compile("SHA-256:.*[a-f0-9]{64}"),
        
        // File paths
        Pattern.compile("Path:.*[/\\\\].*"),
        Pattern.compile("Source:.*[/\\\\].*"),
        
        // OpenRewrite metadata
        Pattern.compile("Rewrite\\d{4}.*"),
        Pattern.compile("/* Generated by OpenRewrite.*")
    );
    
    private static final String TIMESTAMP_PLACEHOLDER = "Generated at EPOCH";
    private static final String HASH_PLACEHOLDER = "Source hash HASH_REDACTED";
    private static final String PATH_PLACEHOLDER = "Path PATH_REDACTED";
    private static final String OPENREWRITE_PLACEHOLDER = "/* Generated by OpenRewrite */";
    
    /**
     * Normalize content by replacing dynamic metadata with canonical values.
     * 
     * @param content Original content
     * @return Normalized content
     */
    public String normalize(String content) {
        String normalized = content;
        
        for (Pattern pattern : NORMALIZATION_PATTERNS) {
            normalized = pattern.matcher(normalized).replaceAll(match -> {
                String matched = match.group();
                if (matched.contains("Generated at") || matched.contains("Generated:")) {
                    return TIMESTAMP_PLACEHOLDER;
                } else if (matched.contains("Source hash") || matched.contains("SHA-256:")) {
                    return HASH_PLACEHOLDER;
                } else if (matched.contains("Path:") || matched.contains("Source:")) {
                    return PATH_PLACEHOLDER;
                } else if (matched.contains("Rewrite") || matched.contains("OpenRewrite")) {
                    return OPENREWRITE_PLACEHOLDER;
                }
                return matched;
            });
        }
        
        return normalized;
    }
    
    /**
     * Normalize a file by replacing dynamic metadata.
     * 
     * @param filePath Path to the file
     * @param content File content
     * @return Normalized content
     */
    public String normalizeFile(Path filePath, String content) {
        // Additional file-specific normalization
        String normalized = normalize(content);
        
        // Remove line numbers if present
        normalized = normalized.replaceAll("^\\d+:\\s*", "");
        
        return normalized;
    }
}
